site_name: LASER
theme:
  name: material

nav:
  - API: api.md
  - Glossary: glossary.md
  - Contribute: contribute.md
  - What's New: whatsnew.md
  - Index: index.md
  - Getting Started: get-started.md
  - Tutorial: notebooks/index.md
  - Reference: reference/laser-generic.md

plugins:
  - search
  - pdf-export:
      verbose: true
  - with-pdf:
      output_path: site/documentation.pdf
      cover_title: "LASER-Generic Docs"
      toc_title: "Table of Contents"
      exclude_pages:
        - changelog.md  # (if you want to skip any pages)

